### ISSUE TITLE
biased shift of cube2equi and equi2cube

### ISSUE THREAD

**Issue by qsh-zh** [haruishi43/equilib#8] opened 2022-08-31 10:05 UTC
I find there are shifts if we run cube2equi and equi2cube. How can we avoid or decrease such shifts

```py
cube_xt = rearrange(xt, "(b n) c h w -> b c h (n w)", n=6)

for _ in range(10):
    rec_equi_xt = cube2equi(
        cubemap = cube_xt,
        cube_format="horizon",
        height = height,
        width = width,
        # mode="bilinear",
        mode="bicubic",
        # mode="nearest",
    )

    cube_xt = equi2cube(
        equi=rec_equi_xt[None],
        rots=[{"roll": 0, "pitch": 0, "yaw": 0}],
        w_face=64,
        cube_format="horizon",
        # mode="bilinear",
        mode="bicubic",
        # mode="nearest",
    )

cube_xt = rearrange(cube_xt, "b c h (n w) -> (b n) c h w", n=6)
# show cube and xt
```

![image](https://user-images.githubusercontent.com/28699575/187653692-161d5589-91ce-461b-8fbd-01a4c2fc8424.png)
![image](https://user-images.githubusercontent.com/28699575/187653733-f7d68102-8a1a-4245-8c40-1763bc4d3f39.png)

**Comment by haruishi43** [comment] 2022-09-01 02:18
Thanks for submitting an issue.

Yeah, I've been struggling to make `cube2equi` -> `equi2cube` conversion as robust as possible and I've seen minor bias in my tests, but I haven't seen cubemaps distorting that much.

Would you mind testing this in your notebook to see if a cubemap will transform the same way it did for me?
You can download a cubemap horizon image I used [here](http://wiki.simigon.com/wiki/index.php?title=Dds_cubemaps)

```python
cubestrip = Image.open(osp.join('other_data', 'Cubestrip.jpg'))
cubemap = np.array(cubestrip)

plt.imshow(cubemap)

chw_cubemap = cubemap.transpose(2, 0, 1)
equi = equilib.cube2equi(
    cubemap=chw_cubemap,
    cube_format="horizon",
    height=200,
    width=400,
    mode="bilinear",
)
plt.imshow(equi.transpose(1, 2, 0))

out_cubemap = equilib.equi2cube(
    equi=equi,
    rots={"roll": 0, "pitch": 0, "yaw": 0},
    w_face=100,
    cube_format="horizon",
    mode="bilinear",
)
plt.imshow(out_cubemap.transpose(1, 2, 0))
```

Original Cubemap:
![29faeb3c-f3f7-4202-98f3-a0e6bb56b7bc](https://user-images.githubusercontent.com/7902640/187818048-73981d73-2527-4c3b-8045-4ac15872001d.png)

Output Cubemap:
![bff5c131-1d95-4bb6-a583-f8c6b0b2cd62](https://user-images.githubusercontent.com/7902640/187818080-bac04958-adf1-45e3-a6b8-5f295b8e4a4a.png)

**Comment by haruishi43** [comment] 2022-09-01 02:35
Oh, nvm. I misunderstood your question, you looped this 10 times.

When iterating the same transform on the same data many times, it does seem the shifts increase quite a bit.

I will take a look in the internals when I have time, but it seems really hard to make the transform robust since this transform is irreversible.

**Comment by qsh-zh** [comment] 2022-09-01 05:21
@haruishi43  Thanks for your reply. I find large `w_face` can reduce distortion compared with `w_face`. Do you have materials/note to explain math for cube2equi and equi2cube?

**Comment by haruishi43** [comment] 2022-09-01 05:50
@qsh-zh I will document each algorithm in the future. I haven't got around to it yet :/

All algorithms (`equi2cube`, `cube2equi`, etc...) essentially does the same thing.
1. create a grid of coordinates for each of the pixels of the output array.
2. translate the coordinates if we're given a rotation 
3. sample pixels from the input image ([`grid_sample`](https://github.com/haruishi43/equilib/tree/master/equilib/grid_sample)

For `cube2equi`:
- sampling grids can be formed directly using [`create_equi_grid`](https://github.com/haruishi43/equilib/blob/3381ff85d9f9ddcfb1dfae3a75c31fc012f1a8b8/equilib/cube2equi/numpy.py#L146). This (should) map which face and which pixels should be mapped to the equirectangular image. I feel this part of the algorithm is the cause of this shift.

For `equi2cube`:
- xyz grids are made using [`create_xyz_grid`](https://github.com/haruishi43/equilib/blob/3381ff85d9f9ddcfb1dfae3a75c31fc012f1a8b8/equilib/numpy_utils/grid.py#L100) and converted to pixel (latitude-longitude) grids using [`convert_grid`](https://github.com/haruishi43/equilib/blob/3381ff85d9f9ddcfb1dfae3a75c31fc012f1a8b8/equilib/equi2cube/numpy.py#L89)

**Comment by haruishi43** [comment] 2022-09-27 22:12
@Oletus Thanks for investigating! I Would you like to create a PR?

**Comment by haruishi43** [comment] 2022-10-09 02:04
closing this! thanks to @Oletus

**Closed by haruishi43** 2022-10-09 02:04 UTC
